version: "3.8"

services:
  app:
    image: thefatandfurious/goserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./static:/static
      - ./db:/db
      - ./public:/public
      - ./web/templates:/web/templates
      - ./.env:/.env
    env_file:
      - ./.env

volumes:
  dbdata:
